# version: "2"
# services:
#   backend:
#     build: backend
#     ports:
#       - "3500:8080"
#     # volumes:
#     #   - ./www:/var/www/html/
#     # links:
#     #     - db
#     networks:
#       - default
# db:
#     image: mysql:5.7.13
#     ports:
#         - "3306:3306"
#     environment:
#         MYSQL_DATABASE: fatturazione
#         MYSQL_USER: user
#         MYSQL_PASSWORD: test
#         MYSQL_ROOT_PASSWORD: test
#     volumes:
#         - ./db:/docker-entrypoint-initdb.d/
#         - persistent:/var/lib/mysql
#     networks:
#         - default
# phpmyadmin:
#     image: phpmyadmin/phpmyadmin:4.8.2
#     links:
#         - db:db
#     ports:
#         - 8000:80
#     environment:
#         MYSQL_USER: user
#         MYSQL_PASSWORD: test
#         MYSQL_ROOT_PASSWORD: test
# volumes:
#   persistent:

version: "2"
services:
  react:
    image: "node:10"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
    expose:
      - "3000"
    links:
      - node
    ports:
      - "3000:3000"
    command: "yarn start"
    networks:
      - mynet
  node:
    image: "node:10"
    user: "node"
    working_dir: /home/node/app
    # links:
    #   - db
    volumes:
      - ./backend:/home/node/app
    expose:
      - "8080"
    ports:
      - "3500:8080"
    command: "yarn start"
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
