version: "2"
services:
  react:
    image: "node:10"
    user: "node"
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
    expose:
      - "3000"
    links:
      - node
    ports:
      - "3000:3000"
    command: bash -c "yarn && yarn start"
    networks:
      - mynet
  node:
    image: "node:10"
    user: "node"
    working_dir: /home/node/app
    links:
      - db
    volumes:
      - ./backend:/home/node/app
    expose:
      - "8080"
    ports:
      - "3500:8080"
    command: bash -c "yarn && yarn start"
    networks:
      - mynet

  db:
    image: postgres:9.6.15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: gestionale
    networks:
      - mynet
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.7.3
    restart: always
    ports:
      - 4000:8080
    links:
      - db
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  database_data:
    driver: local
